"""
ORM model — rca_reports table.

Stores structured Root Cause Analysis reports generated by the AI agent.
Multiple RCA versions can exist per investigation (e.g., initial draft vs.
updated after sandbox validation).
"""

import uuid
from typing import Any

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import func

from app.db.models.base import Base, UUIDMixin


class RCAReport(Base, UUIDMixin):
    """Structured Root Cause Analysis report."""

    __tablename__ = "rca_reports"

    # ── Foreign key ────────────────────────────────────────────────────────
    investigation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("investigations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Versioning ─────────────────────────────────────────────────────────
    rca_version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1,
        comment="Monotonically increasing version per investigation"
    )
    is_final: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )

    # ── Report body ────────────────────────────────────────────────────────
    incident_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    impact_assessment: Mapped[str | None] = mapped_column(Text, nullable=True)
    what_failed: Mapped[str | None] = mapped_column(Text, nullable=True)
    why_it_happened: Mapped[str | None] = mapped_column(Text, nullable=True)
    action_proposed: Mapped[str | None] = mapped_column(Text, nullable=True)
    recovery_status: Mapped[str | None] = mapped_column(
        String(100), nullable=True
    )
    long_term_prevention: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── AI quality signals ─────────────────────────────────────────────────
    confidence_score: Mapped[float | None] = mapped_column(
        Float, nullable=True, comment="0.0 – 1.0"
    )
    ai_reasoning_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Immutable timestamp ────────────────────────────────────────────────
    created_at: Mapped[Any] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # ── JSONB ──────────────────────────────────────────────────────────────
    evidence_found: Mapped[list[Any] | None] = mapped_column(
        JSONB, nullable=True, default=list
    )
    contributing_factors: Mapped[list[Any] | None] = mapped_column(
        JSONB, nullable=True, default=list
    )
    recommendations: Mapped[list[Any] | None] = mapped_column(
        JSONB, nullable=True, default=list
    )

    # ── Relationships ──────────────────────────────────────────────────────
    investigation: Mapped["Investigation"] = relationship(  # noqa: F821
        "Investigation", back_populates="rca_reports"
    )

    __table_args__ = (
        Index("ix_rca_inv_version", "investigation_id", "rca_version"),
    )

    def __repr__(self) -> str:
        return (
            f"<RCAReport id={self.id} inv={self.investigation_id} "
            f"v{self.rca_version}>"
        )
